language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
    - printf "\n" | pecl install apcu-beta
    - echo "apc.enable_cli = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer install
